name: Build and test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    env:
      RUSTFLAGS: -D warnings
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: nightly
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: 1.88.0
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v2

      - name: Install NASM for aws-lc-rs on Windows
        if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1

      - name: Install ninja-build tool for aws-lc-fips-sys on Windows
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-ninja@v6

      - name: Run cargo check
        run: cargo check --all --bins --examples --tests --all-features

      - name: Run cargo check (without dev-dependencies to catch missing feature flags)
        if: matrix.rust == 'nightly'
        run: cargo check -Z features=dev_dep

      - name: Run cargo test
        run: cargo test
